import {NewsSource} from '@lynx_extension/cross/types';

export const DEFAULT_SOURCES: NewsSource[] = [
  // ── News & Publications ────────────────────────────────────────────────────
  {
    id: 'venturebeat-ai',
    name: 'VentureBeat AI',
    type: 'website',
    url: 'https://venturebeat.com/category/ai',
    feedUrl: 'https://venturebeat.com/category/ai/feed/',
    enabled: true,
  },
  {
    id: 'techcrunch-ai',
    name: 'TechCrunch AI',
    type: 'website',
    url: 'https://techcrunch.com/category/artificial-intelligence/',
    feedUrl: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    enabled: true,
  },
  {
    id: 'theverge-ai',
    name: 'The Verge AI',
    type: 'website',
    url: 'https://www.theverge.com/ai-artificial-intelligence',
    feedUrl: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    enabled: true,
  },
  {
    id: 'arstechnica-ai',
    name: 'Ars Technica AI',
    type: 'website',
    url: 'https://arstechnica.com/ai/',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/technology-lab',
    enabled: true,
  },
  {
    id: 'mit-tech-review-ai',
    name: 'MIT Technology Review AI',
    type: 'website',
    url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    feedUrl: 'https://www.technologyreview.com/feed/',
    enabled: true,
  },
  {
    id: 'arxiv-ai',
    name: 'arXiv AI',
    type: 'website',
    url: 'https://arxiv.org/list/cs.AI/recent',
    feedUrl: 'https://rss.arxiv.org/rss/cs.AI',
    enabled: true,
  },
  {
    id: 'latent-space',
    name: 'Latent Space',
    type: 'website',
    url: 'https://www.latent.space/archive',
    feedUrl: 'https://www.latent.space/feed',
    enabled: true,
  },
  {
    id: 'therundown-ai',
    name: 'The Rundown AI',
    type: 'website',
    url: 'https://www.therundown.ai/',
    feedUrl: 'https://www.therundown.ai/subscribe/rss',
    enabled: true,
  },

  // ── Company Blogs ──────────────────────────────────────────────────────────
  {
    id: 'openai-news',
    name: 'OpenAI News',
    type: 'website',
    url: 'https://openai.com/news',
    feedUrl: 'https://openai.com/news/rss.xml',
    enabled: true,
  },
  {
    id: 'deepmind-blog',
    name: 'Google DeepMind Blog',
    type: 'website',
    url: 'https://deepmind.google/blog/',
    feedUrl: 'https://deepmind.google/blog/rss.xml',
    enabled: true,
  },
  {
    id: 'anthropic-news',
    name: 'Anthropic News',
    type: 'website',
    url: 'https://anthropic.com/news',
    feedUrl: 'https://www.anthropic.com/feed.xml',
    enabled: true,
  },
  {
    id: 'huggingface-blog',
    name: 'Hugging Face Blog',
    type: 'website',
    url: 'https://huggingface.co/blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    enabled: true,
  },

  // ── YouTube Channels ───────────────────────────────────────────────────────
  {
    id: 'youtube-mreflow',
    name: 'Matt Wolfe',
    type: 'youtube',
    url: 'https://www.youtube.com/@mreflow',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UChpleBmo18P08aKCIgti38g',
    enabled: true,
  },
  {
    id: 'youtube-fireship',
    name: 'Fireship',
    type: 'youtube',
    url: 'https://www.youtube.com/@Fireship',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA',
    enabled: true,
  },
  {
    id: 'youtube-aiexplained',
    name: 'AI Explained',
    type: 'youtube',
    url: 'https://www.youtube.com/@aiexplained-official',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw',
    enabled: true,
  },
  {
    id: 'youtube-twominutepapers',
    name: 'Two Minute Papers',
    type: 'youtube',
    url: 'https://www.youtube.com/@TwoMinutePapers',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg',
    enabled: true,
  },
  {
    id: 'youtube-matthewberman',
    name: 'Matthew Berman',
    type: 'youtube',
    url: 'https://www.youtube.com/@matthew_berman',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCFMqHs0lCPDWyMJDfhahiXw',
    enabled: true,
  },
  {
    id: 'youtube-theaisearch',
    name: 'AI Search',
    type: 'youtube',
    url: 'https://www.youtube.com/@theAIsearch',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCIgnGlGkVRhd4qNFcEwLL4A',
    enabled: true,
  },
  {
    id: 'youtube-bycloud',
    name: 'bycloud',
    type: 'youtube',
    url: 'https://www.youtube.com/@bycloudAI',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCVMmMsaTSfm5cGbnEWBHJbQ',
    enabled: true,
  },
];
